language: clojure
jdk:
 - oraclejdk8
script: lein midje
after_success:
  - lein deploy clojars
after_script:
  - bash -ex test/coveralls.sh
env:
  global:
    - secure: "PXCH9XQXs59Xg1UHa2Jmx4zWaMKLJiUIZ0ceqcOSyQffvKcMsleyNDDqLjj2LnesOVjEZrDIK09E/JuGM0VAmvztsq71wkB612Ltr4OnzXSkusPOzDoRyPtHZ8o5vlMv9x2E2+7QvF9WJU1dFgK08gy2CptdsLwyeL8grhJraT/iIWesND6sFtfsetMn/oFRdAUz2JnFzCHu8DiDFhO8J29KTh1HTH5S9DS89rc2jpJqjQk9uoWQy+RkPjEOHuRd6RuYyhggbIsey/Bj3VmQasCnkR0BzvrY38pKeMIbG68M2A+cVtDmAeVHTMGO9Bf8cu6eql76Ue9djnRIUMyQP2d90C/RubCFg19Sji7mrm89QSX0EyGS4TLG5VsAtZUO5Eg/ZlD87Y/p0RwzkrSqdc1DEn44WI4VC15BIM9Mg79dFiPjfUotazEp4dt/trxZzqY68PA0E23TNaZo0WaoByD8U6ZCj6EX+04d31DJIT8Y/gku+1TUDmg0xY92+Jldk+xTwMVRwOlT6FZ7eJY8sF7yUFYBmkdk4jKptRlpyT4BpNf3C/W+FwtFwXY18+b1lkwYZmL+m8PG+emj67yD+aOtHDYDVmlCJlOwqxG63aAMVYgrOGdcig18UKB46TXfgqfAVZ6brrhO21/rtTt8Q//IcKASNt1bC+WSOlUn20s="
    - secure: "aEssvTXEuAcnYB8uAy8mBgZuG+OtWTm/CZlr7+ND+H4szqJFtafUkY4UfNtmreXceJCS9pDoAjt45V2tKYCGFXkXlkVhBawTL1ihTFhln0rlukzvpwmxs3vuBhzlhREadFlMlShpDavXQAHd48xth8ZSHld13Wv8tdCaI2hTdU1OFs2VjBpDCYz9x080a3tOYkTo1rlg2tOJezOFpOmemz8Vm+LOG4a8CWhSc6y/V08XR7Eii1MRRdeDnhV0elJXWXl5PYOQUfpk66bspzWQ3rpEr5Hnq1TH7fpSkSSmx7IAlgzvPScUo2YTK3Ka4G7YDjwnzjU8J/A4N9DPJIhn5hdcwCNEDWpdfV5JUp0v1pPtz3f+j9r2Fu0ZXONkVYbVIjjvkcX5oUG0aVAFHpQ6eTNKPrLt/RTjm66ApPF7KRPx+ZBv3S6TuaFhNVxBT8+MKy2kjMDXCHP2sY5j1YasRMZHaNaZ152hLMTgRF2+ImW/3kiGoz6GLKsQmTMfBsfJeIz8vwvehFX9sdq0zxH6zl67Qgnpow+o7tZvmeiJ9BZKm5xmpyGevgCJkkdV+ajVuPzawUhaLIWpEmRKZHJ63guMk17Ep0a+uqSgQXmfmRHVz3D3kLUErEOS2gM482QjefH2SOvcK+4S7eOpw+Wl7vq2EEUF9oR2Wy60OY6n3Js="
