dist: trusty
sudo: false
language: clojure
jdk:
- oraclejdk8
before_install:
- ./install-custom-lein.sh
before_script:
- openssl aes-256-cbc -K $encrypted_5bc06a7c8625_key -iv $encrypted_5bc06a7c8625_iv
  -in publish-key.asc.enc -out /tmp/publish-key.asc -d
- gpg --import /tmp/publish-key.asc
script:
- lein midje
- lein cloverage --codecov
after_success:
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
- DEBUG=1 $TRAVIS_BUILD_DIR/_tools/leiningen/bin/lein deploy clojars

