language: clojure
jdk:
 - oraclejdk8
script: lein2 midje
after_success:
  - lein2 deploy clojars
after_script:
  - lein2 cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
